dist: bionic
language: cpp

jobs:
  include:
    - name: linux-gcc
      os: linux
      compiler: gcc
    - name: linux-python
      os: linux
      compiler: gcc
      env: CONFIG="--enable-python-bindings --disable-mpi" PYTHON=2
    - name: linux-python3
      os: linux
      compiler: gcc
      env: CONFIG="--enable-python-bindings --disable-mpi --with-python=python3" PYTHON=3
    - name: linux-clang
      os: linux
      compiler: clang
    - name: osx
      os: osx
      compiler: clang
      env: CONFIG="CXXFLAGS=-std=c++11"

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      brew upgrade python  # upgrade to Python 3
      python -m pip install numpy scipy matplotlib
      brew install fftw
      brew install openblas
      brew install boost
      export PATH="/usr/local/opt/python/libexec/bin:$PATH"
      python -c "import numpy"
    else
      sudo apt-get install -y fftw3-dev
      sudo apt-get install -y libopenblas-dev
      if [ "$PYTHON" = "2" ]; then
        sudo apt-get install -y python-pip python-tk
        sudo python -m pip install numpy scipy matplotlib
      elif [ "$PYTHON" = "3" ]; then
        sudo apt-get install -y python3-pip python3-tk
        sudo python3 -m pip install numpy scipy matplotlib
      fi
      sudo apt-get install -y libboost-python-dev
      sudo apt-get install -y qmtest
    fi

script:
  - ./autogen.sh
  - ./configure $CONFIG
  - make
  - |
    if [ "$TRAVIS_OS_NAME" != osx -a "$PYTHON" != 3 ]; then
      # unfortunately qmtest only supports Python 2
      make check
    fi

notifications:
  irc: "irc.oftc.net#openvsip"

