language: cpp

jobs:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      brew upgrade python  # upgrade to Python 3
      brew install fftw
      brew install openblas
      export PATH="/usr/local/opt/python/libexec/bin:$PATH"
    else
      sudo apt-get install -y fftw3-dev
      sudo apt-get install -y liblapack-dev
    fi

script: ./autogen.sh && ./configure --disable-mpi && make

notifications:
  irc: "irc.oftc.net#openvsip"

