dist: bionic
language: cpp

jobs:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: gcc
      env: CONFIG="--enable-python-bindings --disable-mpi CXXFLAGS=-Wno-deprecated"
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      brew upgrade python  # upgrade to Python 3
      python -m pip install numpy scipy matplotlib
      brew install fftw
      brew install openblas
      brew install boost
      export PATH="/usr/local/opt/python/libexec/bin:$PATH"
    else
      sudo apt-get install -y fftw3-dev
      sudo apt-get install -y libopenblas-dev
      sudo apt-get install -y python-numpy
      sudo apt-get install -y python-scipy
      sudo apt-get install -y python-matplotlib
      sudo apt-get install -y python-tk
      sudo apt-get install -y libboost-python-dev
      sudo apt-get install -y qmtest
    fi

script:
  - ./autogen.sh
  - ./configure $CONFIG
  - make
  - |
    if [ "$TRAVIS_OS_NAME" != "osx" ]; then
      make check
    fi

notifications:
  irc: "irc.oftc.net#openvsip"

